### ISSUE TITLE
Trakt error on Xbox one.

### ISSUE THREAD

**Issue by tdunahoo71** [razzeee/script.trakt#426] opened 2018-01-02 00:49 UTC
Allows me to add trakt but says error when it's done installing. Shows in program add ins but will not start when clicked. Only thing happens is red box in corner says trakt error see log for information. Can not authorize from account settings tab either. Not sure how to view log file or find it

**Comment by razzeee** [comment] 2018-01-02 00:58
Duplicate of #425

**Closed as completed by razzeee** 2018-01-02 00:58 UTC
