### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by renatolond** [razzeee/script.trakt#298] opened 2016-04-26 20:46 UTC
Hello!
Edit: Using Kodi 16.1
Just updated to 3.1.5 and I'm getting this error:

```
22:30:06 91363.218750 T:1725060080   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'login'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/script.trakt/script.py", line 363, in <module>
                                                Main()
                                              File "/home/osmc/.kodi/addons/script.trakt/script.py", line 38, in Main
                                                traktapi.login()
                                            AttributeError: 'module' object has no attribute 'login'
                                            -->End of Python script error report<--
```

After looking around, it seems that it should be trying to do this `traktapi.traktAPI().login()` instead of `traktapi.login()`
But changing that leads to another error:

```
22:38:21 91858.523438 T:1551889392   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: poll() argument after ** must be a mapping, not NoneType
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/script.trakt/script.py", line 364, in <module>
                                                Main()
                                              File "/home/osmc/.kodi/addons/script.trakt/script.py", line 39, in Main
                                                api.login()
                                              File "/home/osmc/.kodi/addons/script.trakt/traktapi.py", line 60, in login
                                                poller = Trakt['oauth/device'].poll(**code)\
                                            TypeError: poll() argument after ** must be a mapping, not NoneType
                                            -->End of Python script error report<--
```

It seems that `from trakt import Trakt` is not importing properly and `code = Trakt['oauth/device'].code()` is none.

**Comment by robbo68** [comment] 2016-04-27 05:03
Fuck off
On 26 Apr 2016 21:46, "renatolond" notifications@github.com wrote:

Hello!
Just updated to 3.1.5 and I'm getting this error:

22:30:06 91363.218750 T:1725060080   ERROR: EXCEPTION Thrown
(PythonToCppException) : -->Python callback/script returned the
following error<--
                                             - NOTE: IGNORING THIS CAN
LEAD TO MEMORY LEAKS!
                                            Error Type: <type
'exceptions.AttributeError'>
                                            Error Contents: 'module'
object has no attribute 'login'
                                            Traceback (most recent call last):
                                              File
"/home/osmc/.kodi/addons/script.trakt/script.py", line 363, in
<module>
                                                Main()
                                              File
"/home/osmc/.kodi/addons/script.trakt/script.py", line 38, in Main
                                                traktapi.login()
                                            AttributeError: 'module'
object has no attribute 'login'
                                            -->End of Python script
error report<--

After looking around, it seems that it should be trying to do this
traktapi.traktAPI().login() instead of traktapi.login()
But changing that leads to another error:

22:38:21 91858.523438 T:1551889392   ERROR: EXCEPTION Thrown
(PythonToCppException) : -->Python callback/script returned the
following error<--
                                             - NOTE: IGNORING THIS CAN
LEAD TO MEMORY LEAKS!
                                            Error Type: <type
'exceptions.TypeError'>
                                            Error Contents: poll()
argument after *\* must be a mapping, not NoneType
                                            Traceback (most recent call last):
                                              File
"/home/osmc/.kodi/addons/script.trakt/script.py", line 364, in
<module>
                                                Main()
                                              File
"/home/osmc/.kodi/addons/script.trakt/script.py", line 39, in Main
                                                api.login()
                                              File
"/home/osmc/.kodi/addons/script.trakt/traktapi.py", line 60, in login
                                                poller =
Trakt['oauth/device'].poll(*_code)\
                                            TypeError: poll() argument
after *_ must be a mapping, not NoneType
                                            -->End of Python script
error report<--

It seems that from trakt import Trakt is not importing properly and code =
Trakt['oauth/device'].code() is none.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
https://github.com/trakt/script.trakt/issues/298

**Comment by razzeee** [comment] 2016-04-27 06:11
What os are you on?

**Comment by renatolond** [comment] 2016-04-27 08:05
It's a Linux machine running on a Raspberry Pi 2, Debian based.

**Comment by razzeee** [comment] 2016-04-27 10:43
Sorry, should have seen the OSMC in the log :)
I'll try to have a look later, if my headache doesn't get the best of me until then.

**Comment by razzeee** [comment] 2016-04-27 10:46
So your trying to press the button in the settings when it happens? I guess there is no window showing up after that?

**Comment by renatolond** [comment] 2016-04-27 10:58
> So your trying to press the button in the settings when it happens? I guess there is no window showing up after that?

What happens is that I can click the "how do I login", but the next dialog (the one with the pin) doesn't come up. It says that an error ocurred and then it throws that error to the log.

> Sorry, should have seen the OSMC in the log :)

Don't worry ;)

**Comment by JoshSchreuder** [comment] 2016-04-28 13:02
I also have this issue, same exact steps to reproduce. 
Kodi 16.1 on Lubuntu 15.10

Same with [this forum user](http://forum.kodi.tv/showthread.php?tid=220547&pid=2321411#pid2321411)

**Comment by iairj84** [comment] 2016-04-28 14:20
I am also having this issue as well - On Windows 8.1

I'll add that it already shows my ID logged in, however I was trying to log it out and back in to try and force it to refresh since the plugin was not working otherwise.

Edit: Corrected the issue by deleting all trakt files in the Kodi directory and reinstalling the plugin, this triggered me to connect my trakt account and then the syncing worked as planned.

**Comment by razzeee** [comment] 2016-04-28 21:04
Should be fixed as soon as https://github.com/trakt/script.trakt/pull/302 gets merged.

**Closed as completed** 2016-04-30 19:22 UTC
