### ISSUE TITLE
TimeZone error on NAS without Timezone Name

### ISSUE THREAD

**Issue by clinton-hall** [Razzeee/script.trakt#65] opened 2015-02-01 00:24 UTC
Using current dev branch on Asustro NAS. Plugin loaded into Kodi along with the 3 needed libs.

```
07:30:18 T:140187919726336   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'pytz.exceptions.UnknownTimeZoneError'>
                                            Error Contents: 'local'
                                            Traceback (most recent call last):
                                              File "/usr/local/AppCentral/kodi/.kodi/addons/script.trakt/default.py", line 5, in <module>
                                                import utilities
                                              File "/usr/local/AppCentral/kodi/.kodi/addons/script.trakt/utilities.py", line 21, in <module>
                                                __local = pytz.timezone (str(get_localzone()))
                                              File "/usr/local/AppCentral/kodi/.kodi/addons/script.module.pytz/lib/pytz/__init__.py", line 180, in timezone
                                                raise UnknownTimeZoneError(zone)
                                            UnknownTimeZoneError: 'local'
                                            -->End of Python script error report<--
```

My quick fix here was to hardcode the timezone in `/volume1/.@plugins/AppCentral/kodi/.kodi/addons/script.module.pytz/lib/pytz/__init__.py`

line 166 edited from
`        zone = ascii(zone)`
to
`        zone = 'Australia/Adelaide'`

Not sure if there is an easier solution for this... and I also realize that this particular issue comes from an external lib and calls the system timezone properties... but figured it was worth posting here anyway.

**Comment by Razzeee** [comment] 2015-02-01 02:02
Duplicate of https://github.com/Razzeee/script.trakt/issues/62#issuecomment-72344091

**Closed by Razzeee** 2015-02-01 02:02 UTC

**Comment by clinton-hall** [comment] 2015-02-01 07:23
Sorry about that... I did a search first but hadn't realized this was the same.

**Comment by Razzeee** [comment] 2015-02-01 08:28
Not a problem. It's the same error just different os.
