### ISSUE TITLE
unwanted time delay (10-15sec) between stopping episode/movie and showing rating window

### ISSUE THREAD

**Issue by ghost** [razzeee/script.trakt#346] opened 2017-01-20 10:32 UTC
Hi,
this is my setting:
clean installation of Kodi 17.0-RC3 (2017-01-11)
FireTV 1st gen with Android 5.1.1
Trakt version 3.1.9

After finishing an episode or movie the rating windows should popup immediately.
On Kodi 16 this worked, but on Kodi 17 (since a nightly around mid december 2016), there is a time of 10-15 seconds between stopping the episode/movie and the trakt rating window popup.

The log file contains no errors (in the time after finishing the episode / movie).

best regards,
bread

**Comment by razzeee** [comment] 2017-01-22 12:57
Probably due to your connection / firetv connection. I can't reproduce with
Krypton and Nvidia shield, connected via cable to my router.

**Comment by sharkykh** [comment] 2017-04-21 14:45
This happens to me too, from time to time.

I agree that this is a connection issue.
However, this is usually caused by Trakt.tv API being a bit slow or unresponsive at the time, so there isn't much we can do about it.

Edit:
Forgot to add that this happened on several versions of Kodi ranging from 16.1 to 17.1 (including RC's), on both Windows and OpenELEC, all while connected to a fast, stable, wired connection. Also right after the delay occured I checked https://trakt.tv, and it was quite slow to load.

**Comment by razzeee** [comment] 2017-04-21 15:19
I'll close this then.
Thanks for your feedback, but we can't improve it.

**Closed as completed by razzeee** 2017-04-21 15:19 UTC
