### ISSUE TITLE
Problem with certificate in requests

### ISSUE THREAD

**Issue by gborri** [Razzeee/script.trakt#24] opened 2015-01-27 10:49 UTC
six and request lib are installed on kodi.

08:32:15 T:2517359424   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.SSLError'>
                                            Error Contents: [Errno 185090050] _ssl.c:344: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib
                                            Traceback (most recent call last):
                                              File "/home/mediacenter/.kodi/addons/script.trakt/default.py", line 13, in <module>
                                                traktService().run()
                                              File "/home/mediacenter/.kodi/addons/script.trakt/service.py", line 89, in run
                                                globals.traktapi = traktAPI()
                                              File "/home/mediacenter/.kodi/addons/script.trakt/traktapi.py", line 66, in __init__
                                                self.getToken()
                                              File "/home/mediacenter/.kodi/addons/script.trakt/traktapi.py", line 84, in getToken
                                                self.__token = Trakt['auth'].login(getSetting('username'), getSetting('password'))
                                              File "/home/mediacenter/.kodi/addons/script.trakt/trakt/interfaces/auth.py", line 10, in login
                                                'password': password
                                              File "/home/mediacenter/.kodi/addons/script.trakt/trakt/core/http.py", line 72, in post
                                                return self.request('POST', path, params, data, **kwargs)
                                              File "/home/mediacenter/.kodi/addons/script.trakt/trakt/core/http.py", line 49, in request
                                                response = self.session.send(prepared)
                                              File "/home/mediacenter/.kodi/addons/script.trakt/requests/sessions.py", line 573, in send
                                              File "/home/mediacenter/.kodi/addons/script.trakt/requests/adapters.py", line 431, in send
                                            SSLError: [Errno 185090050] _ssl.c:344: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib
                                            -->End of Python script error report<--

**Comment by Razzeee** [comment] 2015-01-27 12:18
@gborri 
can you let me know which os and which requests version you got in kodi?
Should have been fixed with this https://github.com/kennethreitz/requests/issues/557

**Comment by fernandog** [comment] 2015-01-27 13:12
@Razzeee using raspberry pi. raspbmc OS

**Comment by Razzeee** [comment] 2015-01-27 13:25
@fernandog 
using requests 2.4.3?

**Comment by fernandog** [comment] 2015-01-27 13:31
>>> requests.__version__
'2.5.0'
>>>

**Comment by gborri** [comment] 2015-01-27 13:42
ubuntu 14.04
requests 2.4.3

**Comment by Razzeee** [comment] 2015-01-27 18:47
@fuzeman 
maybe you have an idea what could be causing this?

**Comment by tdragonite** [comment] 2015-01-27 19:38
Look at this in another project with similar problem.
https://github.com/dersteppenwolf/qgis-cartodb/commit/000f4410f7861f2fe52b5f01f63c90e9d3381c66

**Comment by fuzeman** [comment] 2015-01-28 06:37
@gborri @fernandog
Which version of XBMC/Kodi/raspbmc are you using?

I'll try reproduce this first (in a VM, or a Raspberry Pi), then it should be fairly simple to work out what is causing this error.

**Comment by gborri** [comment] 2015-01-28 07:22
Kodi 14.0 stable

**Comment by fernandog** [comment] 2015-01-28 08:32
Same

**Comment by fernandog** [comment] 2015-01-28 18:17
Related?
https://github.com/midgetspy/Sick-Beard/pull/912

**Comment by fuzeman** [comment] 2015-01-28 23:42
I'm unable to see this issue on a fresh install of raspbmc - using this older version of the plugin: https://github.com/Razzeee/script.trakt/tree/35626e0084ebe89f4bb0e5d03e3b89d0bae5ea55 (the latest version where "requests" was still bundled, matching the reported stack trace).

-------------------

I finally managed to reproduce this exact issue after running the following commands (basically blocking kodi from accessing "cacert.pem"):
```
sudo chown root:root /home/pi/.kodi/addons/script.trakt/requests/cacert.pem
sudo chmod 640 /home/pi/.kodi/addons/script.trakt/requests/cacert.pem
```

So, could you double-check the permissions of ```script.trakt/requests/cacert.pem``` on your system, as this seems to be a factor in this issue. The permissions should be set to 644 (```-rw-r--r--```).

**Comment by fernandog** [comment] 2015-01-29 00:03
@fuzeman I don't have this file

**Closed** 2015-01-29 12:30 UTC
Labels: bug

**Comment by fernandog** [comment] 2015-01-29 12:33
New installs will have this problem, wont they?

**Comment by Razzeee** [comment] 2015-01-29 12:48
If they do, it's a problem with the requests module for kodi. Should create an issue there
